# Data Transformation

## Contoh 14: Rescale Data antara 0 dan 1

In [5]:
# importing libraries
import pandas
import scipy
import numpy
from sklearn.preprocessing import MinMaxScaler

# Open data set
url = r'C:\Users\ACER\Documents\MY-CODE\Kuliah\data_nggenah.csv'
# data parameters
names = ['Duration','Date','Pulse','Maxpulse','Calories']

# preparation of dataframe using the data at given link and defined columns list
dataframe = pandas.read_csv(url, names = names)
array = dataframe.values

# Select column to rescale
calories = array[:,4].reshape(-1,1)

# Rescaling data
scaler = MinMaxScaler(feature_range=(0, 1))
rescaledX = scaler.fit_transform(calories)
print(rescaledX)

[[0.85407098]
 [1.        ]
 [0.70981211]
 [0.58956159]
 [0.84759916]
 [0.6263048 ]
 [0.78079332]
 [0.52881002]
 [0.40730689]
 [0.56158664]
 [0.6874739 ]
 [0.52338205]
 [0.52338205]
 [0.72087683]
 [0.79185804]
 [0.57411273]
 [0.44926931]
 [0.6263048 ]
 [0.        ]
 [0.6743215 ]
 [0.50730689]
 [0.76033403]
 [0.58872651]
 [0.6263048 ]
 [0.51356994]
 [0.        ]
 [0.58455115]
 [0.79394572]
 [0.50730689]]


## Contoh 15: Binerisasi Data  

In [6]:
from sklearn.preprocessing import Binarizer 
import pandas as pd
import numpy as np

# Open data set
url = r'C:\Users\ACER\Documents\MY-CODE\Kuliah\data_nggenah.csv'

# Read the CSV file into a DataFrame
dataframe = pd.read_csv(url, names=names)

# Replace missing values (NaN) in the 'Pulse' column with a specific value, e.g., 0
dataframe['Pulse'].fillna(0, inplace=True)

# Get the 'Pulse' column as a NumPy array
pulse = dataframe['Pulse'].values.reshape(-1, 1)

# Binarize data
binarizer = Binarizer(threshold=100.0).fit(pulse)
binaryX = binarizer.transform(pulse)

print(binaryX[0:5,:])


[[1]
 [1]
 [1]
 [1]
 [1]]


## Contoh 16: Standarisasi Data 

In [7]:
# importing libraries 
from sklearn.preprocessing import StandardScaler 

# preparation of dataframe using the data at given link and defined columns list 
dataframe = pandas.read_csv(url, names = names) 
array = dataframe.values 
 
# Select column to rescale 
calories = array[:,4].reshape(-1,1)
 
# Standardize data 
scaler = StandardScaler().fit(calories) 
rescaledX = scaler.transform(calories) 

print(rescaledX)

[[ 1.21397362]
 [ 1.90736498]
 [ 0.52851807]
 [-0.04286021]
 [ 1.18322236]
 [ 0.1317276 ]
 [ 0.86578998]
 [-0.33152528]
 [-0.90885543]
 [-0.17578502]
 [ 0.42237662]
 [-0.35731666]
 [-0.35731666]
 [ 0.58109281]
 [ 0.91836471]
 [-0.11626645]
 [-0.70946821]
 [ 0.1317276 ]
 [-2.84420097]
 [ 0.35988212]
 [-0.43369883]
 [ 0.76857631]
 [-0.04682812]
 [ 0.1317276 ]
 [-0.40393955]
 [-2.84420097]
 [-0.06666764]
 [ 0.92828448]
 [-0.43369883]]
